create table if not exists public.categories (
    id bigint generated by default as identity primary key,
    name text not null unique,
    is_active boolean not null default true,
    created_at timestamptz not null default now()
);

create table if not exists public.finish_types (
    id bigint generated by default as identity primary key,
    name text not null unique,
    is_active boolean not null default true,
    created_at timestamptz not null default now()
);

create table if not exists public.occasion_types (
    id bigint generated by default as identity primary key,
    name text not null unique,
    is_active boolean not null default true,
    created_at timestamptz not null default now()
);

alter table public.categories enable row level security;
alter table public.finish_types enable row level security;
alter table public.occasion_types enable row level security;

create policy "Public can read active categories"
on public.categories for select
to anon, authenticated
using (is_active = true);

create policy "Public can read active finish types"
on public.finish_types for select
to anon, authenticated
using (is_active = true);

create policy "Public can read active occasion types"
on public.occasion_types for select
to anon, authenticated
using (is_active = true);
