create table if not exists public.products (
    id bigint generated by default as identity primary key,
    product_code text not null unique,
    name text not null,
    description text,
    short_description text,
    price numeric(12,2) not null check (price >= 0),
    offer_price numeric(12,2) check (offer_price is null or offer_price >= 0),
    offer_label text,
    delivery_time text,
    stock_count integer not null default 0 check (stock_count >= 0),
    category_id bigint references public.categories(id),
    finish_type_id bigint references public.finish_types(id),
    occasion_type_id bigint references public.occasion_types(id),
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.product_images (
    id bigint generated by default as identity primary key,
    product_id bigint not null references public.products(id) on delete cascade,
    image_path text not null,
    image_url text not null,
    is_primary boolean not null default false,
    sort_order integer not null default 0,
    created_at timestamptz not null default now()
);

alter table public.products enable row level security;
alter table public.product_images enable row level security;

create policy "Public can read active products"
on public.products for select
to anon, authenticated
using (is_active = true);

create policy "Public can read product images"
on public.product_images for select
to anon, authenticated
using (
    exists (
        select 1
        from public.products p
        where p.id = product_images.product_id
          and p.is_active = true
    )
);

create index if not exists idx_products_category_id
    on public.products(category_id);

create index if not exists idx_products_created_at
    on public.products(created_at desc);

create index if not exists idx_product_images_product_id
    on public.product_images(product_id);
